name: pull-build-test

on:
  pull_request:
    branches:
      - main

jobs:
  flutter-build:
    name: Run flutter build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: aptiche
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subsito/flutter-action@v1
        with:
          channel: "stable"
      - name: Decode Google Services JSON
        run: echo ${{secrets.ANDROID_FIREBASE_JSON}} | base64 --decode > android/app/google-services.json
      - name: Flutter Build
        run: flutter clean
      - run: flutter pub get
      - run: flutter build apk
