name: pull-build-test

on:
  pull_request:
    branches:
      - main

jobs:
  flutter-build:
    name: Run flutter build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: aptiche
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - name: Flutter Get Depedencies
        run: flutter clean
      - run: flutter pub get
      - name: Flutter Build
        run: |
          mkdir $HOME/private
          gpg --quiet --batch --yes --decrypt --passphrase="$ANDROID_FIREBASE_JSON" \
          --output $HOME/private/services.tar services.tar.gpg
          tar xvf $HOME/private/services.tar
          flutter build apk
        env:
          ANDROID_FIREBASE_JSON: ${{ secrets.ANDROID_FIREBASE_JSONANDROID_FIREBASE_JSON }}
